[package]
name = "axum_api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.8"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = [
  "postgres",
  "runtime-tokio",
  "tls-native-tls",
  "uuid",
] }
tokio = { version = "1.50.0", features = ["full"] }
uuid = { version = "1.22.0", features = ["serde", "v4"] }
async-trait = "0.1.89"
