/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appSettingsRouteRouteImport } from './routes/(app)/settings/route'
import { Route as appAppLayoutRouteRouteImport } from './routes/(app)/_appLayout/route'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appSettingsPreferencesRouteImport } from './routes/(app)/settings/preferences'
import { Route as appAppLayoutWorkoutRouteImport } from './routes/(app)/_appLayout/workout'

const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRouteRoute = appSettingsRouteRouteImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppLayoutRouteRoute = appAppLayoutRouteRouteImport.update({
  id: '/(app)/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/(app)/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsPreferencesRoute = appSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appAppLayoutWorkoutRoute = appAppLayoutWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => appAppLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof appSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/workout': typeof appAppLayoutWorkoutRoute
  '/settings/preferences': typeof appSettingsPreferencesRoute
  '/profile': typeof appProfileIndexRoute
  '/settings/': typeof appSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/workout': typeof appAppLayoutWorkoutRoute
  '/settings/preferences': typeof appSettingsPreferencesRoute
  '/profile': typeof appProfileIndexRoute
  '/settings': typeof appSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_appLayout': typeof appAppLayoutRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/_appLayout/workout': typeof appAppLayoutWorkoutRoute
  '/(app)/settings/preferences': typeof appSettingsPreferencesRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/login'
    | '/register'
    | '/workout'
    | '/settings/preferences'
    | '/profile'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/workout'
    | '/settings/preferences'
    | '/profile'
    | '/settings'
  id:
    | '__root__'
    | '/(app)/_appLayout'
    | '/(app)/settings'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(app)/_appLayout/workout'
    | '/(app)/settings/preferences'
    | '/(app)/profile/'
    | '/(app)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppLayoutRouteRoute: typeof appAppLayoutRouteRouteWithChildren
  appSettingsRouteRoute: typeof appSettingsRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_appLayout': {
      id: '/(app)/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/preferences': {
      id: '/(app)/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof appSettingsPreferencesRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/_appLayout/workout': {
      id: '/(app)/_appLayout/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof appAppLayoutWorkoutRouteImport
      parentRoute: typeof appAppLayoutRouteRoute
    }
  }
}

interface appAppLayoutRouteRouteChildren {
  appAppLayoutWorkoutRoute: typeof appAppLayoutWorkoutRoute
}

const appAppLayoutRouteRouteChildren: appAppLayoutRouteRouteChildren = {
  appAppLayoutWorkoutRoute: appAppLayoutWorkoutRoute,
}

const appAppLayoutRouteRouteWithChildren =
  appAppLayoutRouteRoute._addFileChildren(appAppLayoutRouteRouteChildren)

interface appSettingsRouteRouteChildren {
  appSettingsPreferencesRoute: typeof appSettingsPreferencesRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appSettingsRouteRouteChildren: appSettingsRouteRouteChildren = {
  appSettingsPreferencesRoute: appSettingsPreferencesRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appSettingsRouteRouteWithChildren =
  appSettingsRouteRoute._addFileChildren(appSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAppLayoutRouteRoute: appAppLayoutRouteRouteWithChildren,
  appSettingsRouteRoute: appSettingsRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  appProfileIndexRoute: appProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
